export default {
    SUCESS: 'SUCESS',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    UNAUTHORIZED: 'UNAUTHORIZED',
    NOT_FOUND: 'NOT_FOUND',
    UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
    MISSING_FIELDS: 'MISSING_FIELDS',
}