module.exports = {
    SUCCESS: 'SUCCESS',
    GENERIC_ERROR: 'GENERIC_ERROR',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_TOKEN: 'INVALID_TOKEN',
    NOT_FOUND: 'NOT_FOUND',
    UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
    INVALID_INPUT: 'INVALID_INPUT',
    DUPLICATE_RECORD: 'DUPLICATE_RECORD',
    TIMEOUT: 'TIMEOUT',
}